# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_logo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_cost', models.FloatField(default=0.0)),
                ('item_date', models.DateField()),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Category')),
            ],
        ),
    ]
